(this.VMK_WebPack = this.VMK_WebPack || []).push([
	[0], {
		257: function(e, t, a) {
			e.exports = a(520)
		},
		316: function(e, t) {},
		318: function(e, t) {},
		330: function(e, t) {},
		332: function(e, t) {},
		520: function(e, t, a) {
			"use strict";
			a.r(t);
			a(258);
			var n = a(0),
				r = a.n(n),
				l = a(50),
				s = a.n(l),
				o = a(29),
				i = a(44),
				c = a.n(i),
				d = a(57),
				u = a(75),
				m = a(15),
				h = a(22),
				p = a(17),
				g = a(16),
				f = a(10),
				E = a(11),
				b = a(45),
				w = a(31),
				y = a(244),
				v = a.n(y);
			a(266);

			function S() {
				var e = Object(f.a)([]);
				return S = function() {}, e
			}

			function x() {
				var e = Object(f.a)([]);
				return x = function() {}, e
			}

			function D() {
				var e = Object(f.a)([]);
				return D = function() {}, e
			}

			function k() {
				var e = Object(f.a)([]);
				return k = function() {}, e
			}

			function A() {
				var e = Object(f.a)([]);
				return A = function() {}, e
			}

			function T() {
				var e = Object(f.a)([]);
				return T = function() {}, e
			}

			function C() {
				var e = Object(f.a)([]);
				return C = function() {}, e
			}

			function H() {
				var e = Object(f.a)([""]);
				return H = function() {}, e
			}
			
			var M = ["", "", ""],
				W = E.a.div(H(), (function(e) {}), (function(e) {}), (function(e) {}), (function(e) {}), (function(e) {}), (function(e) {})),
				B = E.a.div(C()),
				N = E.a.div(T(), (function(e) {})),
				P = E.a.div(A(), (function(e) {})),
				X = E.a.div(k(), (function(e) {})),
				O = E.a.div(D()),
				I = E.a.div(x(), (function(e) {}), (function(e) {})),
				U = E.a.div(S(), (function(e) {})),
				j = function(e) {
					Object(p.a)(a, e);
					var t = Object(g.a)(a);
					function a(e) {}
					return Object(h.a)(a, [{
						key: "componentWillMount",
						value: function() {}
					}, {
						key: "componentWillUnmount",
						value: function() {}
					}, {
						key: "render",
						value: function() {}
					}]), a
				}(n.Component),
				F = a(26),
				z = a(34),
				R = a.n(z),
				L = a(13),
				_ = a(248);

			function G() {
				var e = Object(f.a)([""]);
				return e
			}
			
			var V = 192 * 1e-8,
				K = "",
				Q = E.a.div(G()),
				Y = function(e) {}(n.Component),
				J = function(e) {}(n.Component),
				q = function(e) {}(n.Component),
				Z = function(e) {}(n.Component),
				$ = function(e) {}(n.Component),
				ee = function(e) {}(n.Component),
				te = a(249),
				ae = a.n(te);

			function ne() {
				var e = Object(f.a)([]);
				return e
			}

			function re() {
				var e = Object(f.a)([]);
				return e
			}

			function le() {
				var e = Object(f.a)([]);
				return e
			}

			function se() {
				var e = Object(f.a)([""]);
				return e
			}

			function oe() {
				var e = Object(f.a)([""]);
				return e
			}

			var ie = E.a.div(oe()),
				ce = E.a.div(se()),
				de = E.a.div(le()),
				ue = E.a.div(re()),
				me = Object(E.a)(b.a)(ne()),
				he = function(e) {}(n.Component),
				pe = a(250),
				ge = a.n(pe),
				fe = a(30),
				Ee = a(63),
				be = a.n(Ee);

			function we() {
				var e = Object(f.a)([]);
				return e
			}
			var ye = 1,
				ve = 192 * 1e-8,
				Se = E.a.div(we()),
				xe = function(e) {}(n.Component);

			function De() {
				var e = Object(f.a)([]);
				return e
			}
			var ke = E.a.div(De()),
				Ae = function(e) {}(n.Component);

			function Te() {
				var e = Object(f.a)([]);
				return e
			}
			var Ce = E.a.div(Te()),
				He = function(e) {}(n.Component),
				Me = (a(488), function(e) {}(n.Component)),
				We = a(252),
				Be = a.n(We),
				Ne = a(253),
				Pe = a.n(Ne);

			function Xe() {
				var e = Object(f.a)([]);
				return e
			}

			function Oe() {
				var e = Object(f.a)([]);
				return e
			}

			function Ie() {
				var e = Object(f.a)([]);
				return e
			}
			var Ue = E.a.div(Ie()),
				je = E.a.div(Oe()),
				Fe = E.a.div(Xe()),
				ze = function(e) {
					Object(p.a)(a, e);
					var t = Object(g.a)(a);
					function a(e) {
						var n;
						return Object(m.a)(this, a), (n = t.call(this, e)).setError = function(e) {},
							n.createWallet = function(e) {
								// CREATE 12 WORD SEED PHRASE
								return (new L.Mnemonic).toString();
								//console.log((new L.Mnemonic).toString());
							}, n
					}
					return Object(h.a)(a, [{
						key: "render",
						value: function() {
							var e = this;
							window.Generate_12_Words_Seed_Phrase = function(){return e.createWallet()};
							return r.a.createElement("div", null, r.a.createElement(Ue, null,
								r.a.createElement(Fe, {
									onClick: function() {
										e.createWallet()
									}
								})
							))
						}
					}]), a
				}(n.Component),
				Re = a(47),
				Le = a.n(Re),
				_e = a(110);

			function Ge() {
				var e = Object(f.a)([]);
				return e
			}

			function Ve() {
				var e = Object(f.a)([]);
				return e
			}

			function Ke() {
				var e = Object(f.a)([]);
				return e
			}

			function Qe() {
				var e = Object(f.a)([]);
				return e
			}

			var Ye = {},
				Je = E.a.div(Qe()),
				qe = E.a.div(Ke()),
				Ze = E.a.div(Ve()),
				$e = E.a.div(Ge()),
				et = function(e) {
					Object(p.a)(a, e);
					var t = Object(g.a)(a);
					function a(e) {
						var n;
						Object(m.a)(this, a), (n = t.call(this, e)).getModeFromUrl = function() {};
						var h = new Date;
						return h.setDate(h.getDate() - 1), r && new Date(parseInt(r)) > h && l && s && o && i ? n.state = {} : n.state = {}, n
					}
					return Object(h.a)(a, [{
						key: "render",
						value: function() {
							var e = this,
								t = window.location.href.toLowerCase();
							return r.a.createElement(
								Je, null, r.a.createElement(Ze, {}, "" === this.state.mode ? r.a.createElement(Y, {}) : 
								"" === this.state.mode ? r.a.createElement(J, null) : 
								"" === this.state.mode ? r.a.createElement(q, null) : 
								"" === this.state.mode ? r.a.createElement(Z, null) : 
								"" === this.state.mode ? r.a.createElement($, null) : 
								"" === this.state.mode ? r.a.createElement(ee, null) : 
								this.state.hdSeedE && this.state.encryptedPasswordHash ? r.a.createElement(Me, {}) : 
								r.a.createElement(ze, {}), this.state.loading && r.a.createElement($e, null, "")),
								r.a.createElement(qe, null)
							)
						}
					}]), a
				}(n.Component),
				tt = true;

			var nt = document.getElementById("hidden_for_render");
			s.a.render(r.a.createElement(o.a, null, r.a.createElement(et, null)), nt), function() {}()
		}
	},
	[
		[257]
	]
]);

! function(e) {
    function t(t) {
        for (var n, l, a = t[0], f = t[1], i = t[2], c = 0, s = []; c < a.length; c++) l = a[c], Object.prototype.hasOwnProperty.call(o, l) && o[l] && s.push(o[l][0]), o[l] = 0;
        for (n in f) Object.prototype.hasOwnProperty.call(f, n) && (e[n] = f[n]);
        for (p && p(t); s.length;) s.shift()();
        return u.push.apply(u, i || []), r()
    }
    function r() {
        for (var e, t = 0; t < u.length; t++) {
            for (var r = u[t], n = !0, a = 1; a < r.length; a++) {
                var f = r[a];
                0 !== o[f] && (n = !1)
            }
            n && (u.splice(t--, 1), e = l(l.s = r[0]))
        }
        return e
    }
    var n = {},
        o = {
            1: 0
        },
        u = [];

    function l(t) {
        if (n[t]) return n[t].exports;
        var r = n[t] = {
            i: t,
            l: !1,
            exports: {}
        };
        return e[t].call(r.exports, r, r.exports, l), r.l = !0, r.exports
    }
    l.m = e, l.c = n, l.d = function(e, t, r) {
        l.o(e, t) || Object.defineProperty(e, t, {
            enumerable: !0,
            get: r
        })
    }, l.r = function(e) {
        "undefined" != typeof Symbol && Symbol.toStringTag && Object.defineProperty(e, Symbol.toStringTag, {
            value: "Module"
        }), Object.defineProperty(e, "__esModule", {
            value: !0
        })
    }, l.t = function(e, t) {
        if (1 & t && (e = l(e)), 8 & t) return e;
        if (4 & t && "object" == typeof e && e && e.__esModule) return e;
        var r = Object.create(null);
        if (l.r(r), Object.defineProperty(r, "default", {
                enumerable: !0,
                value: e
            }), 2 & t && "string" != typeof e)
            for (var n in e) l.d(r, n, function(t) {
                return e[t]
            }.bind(null, n));
        return r
    }, l.n = function(e) {
        var t = e && e.__esModule ? function() {
            return e.default
        } : function() {
            return e
        };
        return l.d(t, "a", t), t
    }, l.o = function(e, t) {
        return Object.prototype.hasOwnProperty.call(e, t)
    }, l.p = "/";
    var a = this.VMK_WebPack = this.VMK_WebPack || [],
        f = a.push.bind(a);
    a.push = t, a = a.slice();
    for (var i = 0; i < a.length; i++) t(a[i]);
    var p = f;
    r()
}([])
