
--- MSSQL -> TÁCH PHẦN THẬP PHÂN SAU DẤU PHẨY

	SELECT X, (ABS(X) - FLOOR(ABS(X))) AS 'THAP_PHAN' FROM (SELECT 2.938 AS X) AS DATA;

--- CÓ THỂ DÙNG PHÉP CHIA LẤY DƯ TRONG MYSQL + POSTGRESQL

	SELECT X, X % 1 AS THAP_PHAN FROM (SELECT 2.938 AS X) AS DATA;
