/*
    MSSQL -> HƯỚNG DẪN VÔ HIỆU HÓA IDENTITY CACHE TRONG SQL SERVER

    1. TRÁNH HIỆN TƯỢNG NHẢY SỐ ID ĐỘT NGỘT:
    MẶC ĐỊNH, SQL SERVER SẼ LƯU TẠM (CACHE) MỘT KHOẢNG GIÁ TRỊ IDENTITY (THƯỜNG LÀ 1000 GIÁ TRỊ) VÀO BỘ NHỚ ĐỂ TĂNG HIỆU NĂNG CHÈN DỮ LIỆU. 
    VẤN ĐỀ: NẾU SQL SERVER BỊ KHỞI ĐỘNG LẠI ĐỘT NGỘT, BỊ CRASH HOẶC FAILOVER TRONG HỆ THỐNG ALWAYS ON, TẤT CẢ CÁC GIÁ TRỊ ID ĐÃ ĐƯỢC CACHE NHƯNG CHƯA SỬ DỤNG SẼ BỊ MẤT.
    HẬU QUẢ: SAU KHI HỆ THỐNG HOẠT ĐỘNG LẠI, GIÁ TRỊ ID TIẾP THEO SẼ BẮT ĐẦU TỪ ĐIỂM KẾT THÚC CỦA DẢI CACHE TRƯỚC ĐÓ, TẠO RA MỘT KHOẢNG TRỐNG LỚN (VÍ DỤ: ID ĐANG LÀ 10 BỖNG NHẢY VỌT LÊN 1011). 

    2. ĐẢM BẢO TÍNH LIÊN TỤC CHO MỤC ĐÍCH NGHIỆP VỤ:
    NHIỀU DOANH NGHIỆP YÊU CẦU SỐ HÓA ĐƠN HOẶC MÃ HỒ SƠ PHẢI CÓ TÍNH LIÊN TỤC TƯƠNG ĐỐI ĐỂ PHỤC VỤ VIỆC ĐỐI SOÁT VÀ KIỂM TOÁN (AUDITING).
    VÔ HIỆU HÓA CACHE GIÚP GIẢM THIỂU TỐI ĐA CÁC KHOẢNG TRỐNG DO LỖI HỆ THỐNG GÂY RA. 
*/

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = OFF

/*
    3. LƯU Ý QUAN TRỌNG VỀ HIỆU NĂNG:
    ĐÁNH ĐỔI: VIỆC TẮT IDENTITY_CACHE CÓ THỂ LÀM GIẢM HIỆU NĂNG CHÈN (INSERT) DỮ LIỆU, ĐẶC BIỆT LÀ TRONG CÁC HỆ THỐNG CÓ TẦN SUẤT GHI CỰC CAO (HIGH-CONCURRENCY), VÌ MỖI LẦN LẤY ID MỚI, HỆ THỐNG PHẢI GHI TRỰC TIẾP XUỐNG ĐĨA THAY VÌ LẤY TỪ BỘ NHỚ.
    KẾT LUẬN: CHỈ NÊN TẮT NẾU ỨNG DỤNG CỦA BẠN YÊU CẦU KHẮT KHE VỀ VIỆC HẠN CHẾ KHOẢNG TRỐNG ID VÀ KHÔNG QUÁ ƯU TIÊN TỐC ĐỘ INSERT CỰC NHANH. 
*/
