
-- MySQL + MariaDB -> NẾU GIÁ TRỊ LÀ NULL TRẢ VỀ 0

    SELECT IFNULL(id, 0) FROM user;

-- SỬ DỤNG COALESCE THAY THẾ CHO IFNULL
-- HÀM COALESCE HOẠT ĐỘNG TRÊN HẦU HẾT CÁC HỆ THỐNG (MYSQL, POSTGRESQL, SQL SERVER, ORACLE, SQLITE)

    SELECT COALESCE(id, 0) AS id_alias FROM user;
